# 节点2配置文件
node_id: "node2"
address: ":8002"

# 集群节点配置
cluster_nodes:
  node1: "localhost:8001"
  node2: "localhost:8002"
  node3: "localhost:8003"

# 缓存配置
cache_size: 1000        # 每个节点的缓存大小
virtual_nodes: 150      # 虚拟节点数量

# 可选配置
# timeout: 5s           # 请求超时时间
# retry_count: 3        # 重试次数
# log_level: "info"     # 日志级别
